language: node_js

node_js:
  - "10"

sudo: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  yarn: true
  directories:
    - "public/node_modules"

before_script:
  - cd public
  - yarn install

script:
  - yarn test
